(() => {
  "use strict";
  const EZ=window.EZ;
  EZ.activeView="home";
  EZ.viewMeta={
    home:["Home","Overview of your sandbox payment activity."],
    payments:["Payments","Search and inspect every sandbox payment."],
    balances:["Balances","Track sandbox ledger balances and payouts."],
    customers:["Customers","Customer profiles generated by your payment pages."],
    products:["Product catalog","Create products and reusable recurring or one-time prices."],
    subscriptions:["Subscriptions","Recurring subscriptions created from your published payment pages."],
    pages:["Payment pages","Build, preview, publish, duplicate, and share hosted checkouts."],
    risk:["Risk","Sandbox controls for payment attempts and credential safety."],
    developers:["Developers","EZPay objects, API shape, and production rail adapters."],
    settings:["Settings","Workspace branding and payment-page defaults."]
  };

  EZ.setView=(view)=>{
    if(!EZ.viewMeta[view])view="home";
    EZ.activeView=view;
    document.querySelectorAll(".view").forEach((node)=>node.classList.remove("active"));
    EZ.$("view-"+view)?.classList.add("active");
    document.querySelectorAll(".nav-item").forEach((node)=>node.classList.toggle("active",node.dataset.view===view));
    EZ.$("pageTitle").textContent=EZ.viewMeta[view][0];
    EZ.$("pageSubtitle").textContent=EZ.viewMeta[view][1];
    EZ.renderPageActions();
    EZ.renderAll();
    EZ.$("sidebar").classList.remove("open");
  };

  EZ.renderPageActions=()=>{
    const actions={
      products:'<button class="primary-button" data-action="new-product">+ Add product</button>',
      pages:'<button class="primary-button" data-action="new-page">+ Create payment page</button>',
      payments:'<button class="secondary-button" data-action="export-payments">Export CSV</button>',
      customers:'<button class="secondary-button" data-action="export-customers">Export CSV</button>',
      subscriptions:'<button class="secondary-button" data-action="export-subscriptions">Export CSV</button>'
    };
    EZ.$("pageActions").innerHTML=actions[EZ.activeView]||'<button class="primary-button" data-action="new-page">+ Create</button>';
  };

  EZ.renderStats=()=>{
    const m=EZ.metrics();
    EZ.$("homeStats").innerHTML=[
      ["Gross volume",EZ.money(m.gross),m.successful.length+" successful sandbox payments"],
      ["Net balance",EZ.money(m.available),"Available before production settlement"],
      ["Customers",String(EZ.state.customers.length),"Created through checkouts"],
      ["Monthly recurring",EZ.money(m.mrr),m.activeSubs.length+" active subscriptions"]
    ].map((x)=>'<article class="stat-card"><span>'+x[0]+'</span><strong>'+x[1]+'</strong><small>'+x[2]+'</small></article>').join("");
    EZ.$("paymentStats").innerHTML=[
      ["Gross volume",EZ.money(m.gross),"Successful payments"],
      ["Succeeded",String(m.successful.length),"Sandbox authorizations"],
      ["Failed",String(m.failed.length),"Risk/test declines"],
      ["Success rate",EZ.state.payments.length?(Math.round((m.successful.length/EZ.state.payments.length)*1000)/10)+"%":"—","All attempts"]
    ].map((x)=>'<article class="stat-card"><span>'+x[0]+'</span><strong>'+x[1]+'</strong><small>'+x[2]+'</small></article>').join("");
    EZ.$("balanceStats").innerHTML=[
      ["Available",EZ.money(m.available),"Sandbox ledger"],
      ["Pending","$0.00","Settlement not modeled"],
      ["Payouts",EZ.money(EZ.state.payouts.reduce((s,p)=>s+p.amount,0)),EZ.state.payouts.length+" sandbox payouts"],
      ["Currency","USD","Workspace default"]
    ].map((x)=>'<article class="stat-card"><span>'+x[0]+'</span><strong>'+x[1]+'</strong><small>'+x[2]+'</small></article>').join("");
    EZ.$("availableBalance").textContent=EZ.money(m.available);
    EZ.$("subscriptionStats").innerHTML=[
      ["MRR",EZ.money(m.mrr),"Normalized recurring revenue"],
      ["Active",String(m.activeSubs.length),"Active + trialing"],
      ["Products",String(EZ.state.products.length),"Catalog products"],
      ["Payment pages",String(EZ.state.pages.filter((p)=>p.published).length),"Published checkouts"]
    ].map((x)=>'<article class="stat-card"><span>'+x[0]+'</span><strong>'+x[1]+'</strong><small>'+x[2]+'</small></article>').join("");
    EZ.$("blockedCount").textContent=String(m.failed.length);
  };

  EZ.renderChart=()=>{
    const m=EZ.metrics();
    EZ.$("chartValue").textContent=EZ.money(m.gross);
    const chart=EZ.$("volumeChart");
    chart.innerHTML="";
    EZ.state.chartBars.forEach((height,index)=>{
      const node=document.createElement("div");
      node.className="bar";node.style.height=height+"%";node.title="Day "+(index+1);chart.appendChild(node);
    });
    EZ.$("balanceSummary").innerHTML=
      '<div class="balance-row"><span><i class="green"></i>Available</span><strong>'+EZ.money(m.available)+'</strong></div>'+
      '<div class="balance-row"><span><i class="amber"></i>Pending</span><strong>$0.00</strong></div>'+
      '<div class="balance-row"><span><i class="purple"></i>Reserve</span><strong>$0.00</strong></div>';
  };

  EZ.paymentRows=(items)=>{
    if(!items.length)return '<tr><td colspan="6" class="muted-cell">No sandbox payments yet.</td></tr>';
    return items.map((payment)=>{
      const product=EZ.product(payment.productId);
      return '<tr><td class="amount-cell">'+EZ.money(payment.amount,payment.currency)+'</td><td>'+EZ.statusPill(payment.status)+'</td><td>'+
        EZ.escape(payment.customerEmail||"Guest")+'</td><td>'+EZ.escape(product?.name||payment.description||"Payment")+
        '</td><td>'+EZ.escape(payment.method||"Sandbox")+'</td><td>'+EZ.shortTime(payment.created)+'</td></tr>';
    }).join("");
  };

  EZ.renderPayments=()=>{
    const sorted=[...EZ.state.payments].sort((a,b)=>b.created-a.created);
    EZ.$("homePaymentsBody").innerHTML=EZ.paymentRows(sorted.slice(0,5));
    const q=(EZ.$("paymentSearch").value||"").toLowerCase(),status=EZ.$("paymentStatusFilter").value;
    const filtered=sorted.filter((p)=>(!q||[p.customerEmail,p.description,p.method].join(" ").toLowerCase().includes(q))&&(status==="all"||p.status===status));
    EZ.$("paymentsBody").innerHTML=EZ.paymentRows(filtered);
    EZ.$("paymentCount").textContent=EZ.state.payments.length+" total";
  };

  EZ.renderCustomers=()=>{
    const q=(EZ.$("customerSearch").value||"").toLowerCase();
    const rows=[...EZ.state.customers].sort((a,b)=>b.created-a.created).filter((c)=>!q||(c.name+" "+c.email).toLowerCase().includes(q));
    EZ.$("customerCount").textContent=EZ.state.customers.length+" total";
    EZ.$("customersBody").innerHTML=rows.length?rows.map((c)=>{
      const pays=EZ.state.payments.filter((p)=>p.customerId===c.id&&p.status==="succeeded");
      const lifetime=pays.reduce((s,p)=>s+p.amount,0);
      const subs=EZ.state.subscriptions.filter((s)=>s.customerId===c.id&&["active","trialing"].includes(s.status)).length;
      return '<tr><td><strong>'+EZ.escape(c.name||"Customer")+'</strong></td><td>'+EZ.escape(c.email)+'</td><td class="amount-cell">'+EZ.money(lifetime)+'</td><td>'+pays.length+'</td><td>'+subs+'</td><td>'+EZ.shortDate(c.created)+'</td></tr>';
    }).join(""):'<tr><td colspan="6" class="muted-cell">No customers yet.</td></tr>';
  };

  EZ.renderProducts=()=>{
    EZ.$("productsEmpty").classList.toggle("hidden",EZ.state.products.length>0);
    EZ.$("productGrid").innerHTML=EZ.state.products.map((product)=>{
      const initials=product.name.split(/s+/).map((p)=>p[0]).join("").slice(0,2).toUpperCase();
      const prices=product.prices.filter((p)=>p.active).map((p)=>'<div class="price-row"><div><strong>'+EZ.escape(p.nickname)+'</strong><span>'+EZ.escape(p.id)+'</span></div><strong>'+EZ.money(p.amount,p.currency)+' <span>'+EZ.escape(EZ.interval(p))+'</span></strong></div>').join("");
      return '<article class="product-card"><div class="product-icon">'+EZ.escape(initials)+'</div><h3>'+EZ.escape(product.name)+'</h3><p>'+EZ.escape(product.description||"No description")+'</p><div class="price-stack">'+prices+'</div><div class="card-actions"><button data-edit-product="'+product.id+'">Edit</button><button class="primary-mini" data-product-page="'+product.id+'">Create payment page</button></div></article>';
    }).join("");
  };

  EZ.renderSubscriptions=()=>{
    const q=(EZ.$("subscriptionSearch").value||"").toLowerCase();
    const rows=[...EZ.state.subscriptions].sort((a,b)=>b.started-a.started).filter((s)=>{
      const product=EZ.product(s.productId),customer=EZ.customer(s.customerId);
      return !q||[product?.name,customer?.name,s.customerEmail].join(" ").toLowerCase().includes(q);
    });
    EZ.$("subscriptionCount").textContent=EZ.state.subscriptions.length+" total";
    EZ.$("subscriptionsBody").innerHTML=rows.length?rows.map((s)=>{
      const product=EZ.product(s.productId),price=EZ.price(product,s.priceId),customer=EZ.customer(s.customerId);
      return '<tr><td><strong>'+EZ.escape(customer?.name||s.customerEmail)+'</strong><div class="muted-cell">'+EZ.escape(s.customerEmail)+'</div></td><td>'+EZ.escape(product?.name||"Deleted product")+'</td><td class="amount-cell">'+(price?EZ.money(price.amount,price.currency)+" "+EZ.interval(price):"—")+'</td><td>'+EZ.statusPill(s.status)+'</td><td>'+EZ.shortDate(s.started)+'</td><td>'+(s.currentPeriodEnd?EZ.shortDate(s.currentPeriodEnd):"—")+'</td></tr>';
    }).join(""):'<tr><td colspan="6" class="muted-cell">No subscriptions yet. Complete an Aura sandbox checkout to create one.</td></tr>';
  };

  EZ.pageLink=(page)=>location.origin+location.pathname+"#/checkout/"+encodeURIComponent(page.slug);

  EZ.renderPages=()=>{
    const pages=[...EZ.state.pages].sort((a,b)=>(b.updated||b.created)-(a.updated||a.created));
    EZ.$("pagesEmpty").classList.toggle("hidden",pages.length>0);
    EZ.$("paymentPagesGrid").innerHTML=pages.map((page)=>{
      const product=EZ.product(page.productId),price=EZ.price(product,page.priceId);
      return '<article class="payment-page-card"><div class="page-icon" style="background:'+EZ.escape(page.accent)+'18;color:'+EZ.escape(page.accent)+'">'+EZ.escape((page.brand||"E").slice(0,1).toUpperCase())+'</div><h3>'+EZ.escape(page.name)+'</h3><p>'+EZ.escape(product?.name||"Missing product")+(price?" · "+EZ.money(price.amount,price.currency)+" "+EZ.interval(price):"")+'</p><div class="price-stack"><div class="price-row"><div><strong>/'+EZ.escape(page.slug)+'</strong><span>Hosted checkout</span></div>'+EZ.statusPill(page.published?"active":"draft")+'</div></div><div class="card-actions"><button data-edit-page="'+page.id+'">Edit</button><button data-copy-page="'+page.id+'">Copy link</button><button class="primary-mini" data-open-page="'+page.id+'">Open</button></div></article>';
    }).join("");
  };

  EZ.renderPayouts=()=>{
    const rows=[...EZ.state.payouts].sort((a,b)=>b.created-a.created);
    EZ.$("payoutsBody").innerHTML=rows.length?rows.map((p)=>'<tr><td class="amount-cell">'+EZ.money(p.amount)+'</td><td>'+EZ.statusPill(p.status)+'</td><td>'+EZ.escape(p.destination)+'</td><td>'+EZ.shortTime(p.created)+'</td></tr>').join(""):'<tr><td colspan="4" class="muted-cell">No sandbox payouts yet.</td></tr>';
  };

  EZ.renderSettings=()=>{
    EZ.$("settingBusinessName").value=EZ.state.settings.businessName;
    EZ.$("settingAccentColor").value=EZ.state.settings.accent;
    EZ.$("settingAccentHex").value=EZ.state.settings.accent;
    EZ.$("settingSupportEmail").value=EZ.state.settings.supportEmail;
  };

  EZ.renderAll=()=>{EZ.renderStats();EZ.renderChart();EZ.renderPayments();EZ.renderCustomers();EZ.renderProducts();EZ.renderSubscriptions();EZ.renderPages();EZ.renderPayouts();EZ.renderSettings();};
})();